Add software-upate
intel-aero/aero-cockpit-plugins pull request #3
Opened 2017-07-17 08:52 UTC by padmashree9110

Adding software-update plugin, Which will help to update intel-aero image.

2017-07-17 08:54 UTC, padmashree9110 commented
Verified fail condition also by connecting the USb with no image and without USB.

2017-07-17 15:35 UTC, lucasdemarchi requested changes

2017-07-17 15:35 UTC, lucasdemarchi commented on software-update/manifest.json
> +            "label": "Software-update",
Should be "Software Update"

2017-07-17 15:35 UTC, lucasdemarchi commented on software-update/update.html
> +<title>Software-update</title>
"Software Update"

2017-07-17 15:35 UTC, lucasdemarchi commented on software-update/update.html
> +        }
this function is failing parser... ?  Also check your spaces... indent should be 4 spaces.

2017-07-18 04:39 UTC, padmashree9110 commented on software-update/update.html
> +        }
Yes, It is parsing fail condition.

2017-07-18 05:51 UTC, lucasdemarchi commented on software-update/update.html
> +        function fun1() {
`fun1`? you should name functions based on what they are doing.

2017-07-18 06:09 UTC, lucasdemarchi commented
Thank you, pull request merged! [See changes here.](https://github.com/intel-aero/aero-cockpit-plugins/compare/bff30c3~2...bff30c3)

2017-07-18 06:09 UTC, closed without merging

2017-07-18 06:14 UTC, lucasdemarchi commented
Changes like suggested should be amended on the commit rather than creating commits on top with fixes.
Some things missing were:

1. Add the plugin to the Makefile, so when we call "make install" it is automatically installed
1. Renames so functions and messages make more sense

Check my commits on top. Thanks.